### ISSUE TITLE
Align main titles vertically

### ISSUE THREAD

**Issue by noteed** [hypered/design-system#17]
The main titles on these pages are not placed the same way. (The blog post title is slightly above the other one.)
Is is possible to ensure they're placed the same way ?

```
/storybook/iframe.html?id=layouts--blog-post
/storybook/iframe.html?id=sidebar--usage-example
```

**Comment by andyngo** [comment]
Finally figured out what's happening with this alignment bug here.

In the Blog Post example:
No `display: flex` is set on `<main>` container, which causes the margins to collapse, therefore causing the alignment bug.

In the With Sidebar example:
`display: flex` is applied, therefore preserving the margins, and things align correctly here.

For now we can force margins from collapsing by setting `overflow: auto` in the `<article>` element. I'll create a PR for this.

Related reading: https://stackoverflow.com/questions/16485810/how-to-fix-collapsing-top-and-bottom-margins
