### ISSUE TITLE
Make links blue

### ISSUE THREAD

**Issue by noteed** [hypered/design-system#19]
I dislike the current light blue and the hover transition we have on links. Can we just use simple blue links ? I know this is not the color scheme provided by Tachyons but I think we'll have to change it anyway (I don't like the colors of the banners either).

**Comment by andyngo** [comment]
By simple blue links do you mean just removing `.hover-blue` and replacing it with `.blue`?

Agreed, the colors for the banners aren't the best right now.

**Comment by noteed** [comment]
Just `.blue`, although I really prefer a simple `#0000FF` to Tachyons' `.blue`.

**Comment by andyngo** [comment]
@noteed I've added some extra colours here in this PR: https://github.com/hypered/design-system/pull/42

The blue that I chose is `#1a4fcb`, it should be close to `#0000FF`. Let me know if you're okay with the colour palette and I'll update the colours used throughout the design system including the links.

**Comment by noteed** [comment]
I tried your color on https://noteed.com/projects/not-os/ I really prefer the bright `#0000ff`. Anyway I like your palette, and think about letting you take the lead here so you can move faster (and I'm not a designer after all). Maybe make sure you can combine the (background) colors of your screenshot with other colors (e.g. red letters on yellow background, cyan or light blue on blue background, ...) so we have some flexibility ?

**Comment by andyngo** [comment]
I've updated `.blue` to use `#0000ff`, it actually looks pretty good like this. :D

Also added different colour pairings for the Samples like so:
![Screenshot 2019-12-24 at 14 31 45](https://user-images.githubusercontent.com/278293/71398091-539e0b00-265a-11ea-9635-f4dc4cd14438.png)

We can expand on this card-style example if you have an idea where you'd like to use this in your projects. :)

**Comment by noteed** [comment]
Thanks a lot !
