### ISSUE TITLE
Push the footer down the screen on short pages

### ISSUE THREAD

**Issue by noteed** [hypered/design-system#20]
I guess it would be nicer, and it seems it can be done in pure CSS. Do you think there would be any drawback ?

See https://stackoverflow.com/questions/4575826/how-to-push-a-footer-to-the-bottom-of-page-when-content-is-short-or-missing

**Comment by andyngo** [comment]
No big drawback as far as I can tell. Will need to code this up and do a little testing to see if there's any glaring issue.

The Tachyons equivalent would be something like:
```
<div class="flex flex-column space-between mh-100">
  <nav></nav>
  <main>content</main>
  <footer></footer>
</div>
```

Except `min-height: 100vh;` or `.mh-100` will need to be added to `styles.css` ourselves as this is not available in Tachyons by default. I'll create a PR for this when I can.

**Comment by noteed** [comment]
Closing, as it was implemented.
