### ISSUE TITLE
Add examples of correctly sized SVGs

### ISSUE THREAD

**Issue by noteed** [hypered/design-system#26]
The goal is to have SVG elements embedded in a page that are sized correctly. The content of the SVG can be a single solid color, it doesn't matter now.

- For instance one size that has the width of the main content (and say the height computed as a golden ratio). This variant is the most important one, as it can be used for hero header.

- Another could be similar but in the content of a blog post (which has a width smaller that the main element I think).

- Another could have the same with as the blog content.

Talking about hero header, the same SVG can be applied as background-url in CSS. In that case we need a correctly sized `div` with some carefully positioned text. This can be a separate issue if needed.

**Comment by andyngo** [comment]
Hey @noteed , could you illustrate this with a diagram or screenshot? Having some difficulties visualizing this at the moment.
